export const enum Command {
  ARTICLE = "ARTICLE", // https://datatracker.ietf.org/doc/html/rfc3977#section-6.2.1
  BODY = "BODY", // https://datatracker.ietf.org/doc/html/rfc3977#section-6.2.3
  CAPABILITIES = "CAPABILITIES", // https://datatracker.ietf.org/doc/html/rfc3977#section-5.2
  DATE = "DATE", // https://datatracker.ietf.org/doc/html/rfc3977#section-7.1
  GROUP = "GROUP", // https://datatracker.ietf.org/doc/html/rfc3977#section-6.1.1
  HDR = "HDR", // https://datatracker.ietf.org/doc/html/rfc3977#section-8.5
  HEAD = "HEAD", // https://datatracker.ietf.org/doc/html/rfc3977#section-6.2.2
  HELP = "HELP", // https://datatracker.ietf.org/doc/html/rfc3977#section-7.2
  IHAVE = "IHAVE", // https://datatracker.ietf.org/doc/html/rfc3977#section-6.3.2
  LAST = "LAST", // https://datatracker.ietf.org/doc/html/rfc3977#section-6.1.3
  LIST = "LIST", // https://datatracker.ietf.org/doc/html/rfc3977#section-7.6.1
  LISTGROUP = "LISTGROUP", // https://datatracker.ietf.org/doc/html/rfc3977#section-6.1.2
  "MODE READER" = "MODE READER", // https://datatracker.ietf.org/doc/html/rfc3977#section=5.3
  NEWGROUPS = "NEWGROUPS", // https://datatracker.ietf.org/doc/html/rfc3977#section-7.3
  NEWNEWS = "NEWNEWS", // https://datatracker.ietf.org/doc/html/rfc3977#section-7.4
  NEXT = "NEXT", // https://datatracker.ietf.org/doc/html/rfc3977#section-6.1.4
  OVER = "OVER", // https://datatracker.ietf.org/doc/html/rfc3977#section-8.3
  POST = "POST", // https://datatracker.ietf.org/doc/html/rfc3977#section-6.3.1
  QUIT = "QUIT", // https://datatracker.ietf.org/doc/html/rfc3977#section-5.4
  STAT = "STAT", // https://datatracker.ietf.org/doc/html/rfc3977#section-6.2.4
  // Extensions
  "AUTHINFO USER" = "AUTHINFO USER", // https://datatracker.ietf.org/doc/html/rfc4643#section-2.3
  "AUTHINFO PASS" = "AUTHINFO PASS",
  "AUTHINFO SASL" = "AUTHINFO SASL", // https://datatracker.ietf.org/doc/html/rfc4643#section-2.4
}

export const MultiLineResponseCodes = [
  100, // Generated by: HELP
  101, // Generated by: CAPABILITIES
  // 211, // Generated by: LISTGROUP (multi-line), GROUP (not multi-line).
  215, // Generated by: LIST
  220, // Generated by: ARTICLE
  221, // Generated by: HEAD
  222, // Generated by: BODY
  224, // Generated by: OVER
  225, // Generated by: HDR
  230, // Generated by: NEWNEWS
  231, // Generated by: NEWGROUPS
];

// deno-lint-ignore no-empty-interface
export interface Article extends RequestInit {}
